### ISSUE TITLE
Docker marking container as unhealthy

### ISSUE THREAD

**Issue by TheGorf** [visibilityspots/dockerfile-cloudflared#31] opened 2021-02-01 03:15 UTC
I'm running this container on some raspberry pi's and have done so for some time. I was setting it up tonight and for whatever reason it keeps marking the container as unhealthy with the recurring complaint:

time.c:118: Operation not permitted timer.c:634: fatal error: RUNTIME_CHECK(isc_time_now((&now)) == 0) failed Aborted

I can't really figure out what, if anything, is actually wrong because the container functionally works just fine. So I think it's the health check and specifically the nslookup binary that is throwing the error not the command itself. Consoling into the container and just running "nslookup" throws that error.  I'm happy to help troubleshoot this if it is helpful.

**Comment by visibilityspots** [comment] 2021-02-01 15:26
Hi @TheGorf  thanks for opening an issue, I'll need some more background information though.

Which OS are you using on the pi? What's the command you use to start the container and how are you performing the nslookup in the container itself?

**Comment by git-clone** [comment] 2021-02-01 16:15
This could it be duplicate of 30#
I use this image on my Pi4 do you have the problem on this one?
 image: visibilityspots/cloudflared:alpine-3.12

**Comment by TheGorf** [comment] 2021-02-01 21:11
I'm running it on RPi 4: 
`Linux raspberrypi 5.4.83-v7l+ #1379 SMP Mon Dec 14 13:11:54 GMT 2020 armv7l GNU/Linux`

The container isn't anything special. Just a standard pull without any tags.  This is my run command:

`dockerun --name cloudflared --rm -dit --network pihole_network --ip=172.21.0.11 visibilityspots/cloudflared`

**Comment by TheGorf** [comment] 2021-02-01 21:19
Ok, this appears to be a duplicate of #30.  I appear to have very similar issues with the container time.  @git-clone I went ahead a redeployed the container using the alpine-3.12 tag and now everything appears to be honky-dory and the container is marked as "healthy"

**Comment by visibilityspots** [comment] 2021-02-02 08:39
I'll close the issue then. Thanks @git-clone for your help, much appreciated!

**Closed by visibilityspots** 2021-02-02 08:39 UTC
